export const ORDER_STATES = {
  ORDER_PLACED: 'ORDER_PLACED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_VERIFICATION: 'PAYMENT_VERIFICATION',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  PRODUCTION: 'PRODUCTION',
  QUALITY_CHECK: 'QUALITY_CHECK',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURNED: 'RETURNED',
} as const;

export type OrderState = (typeof ORDER_STATES)[keyof typeof ORDER_STATES];

export const TERMINAL_ORDER_STATES: readonly OrderState[] = [
  ORDER_STATES.DELIVERED,
  ORDER_STATES.CANCELLED,
  ORDER_STATES.RETURNED,
];

export const PAYMENT_ORDER_STATES: readonly OrderState[] = [
  ORDER_STATES.ORDER_PLACED,
  ORDER_STATES.PAYMENT_PENDING,
  ORDER_STATES.PAYMENT_VERIFICATION,
  ORDER_STATES.PAYMENT_CONFIRMED,
];

export const FULFILLMENT_ORDER_STATES: readonly OrderState[] = [
  ORDER_STATES.ORDER_CONFIRMED,
  ORDER_STATES.PRODUCTION,
  ORDER_STATES.QUALITY_CHECK,
  ORDER_STATES.PACKED,
  ORDER_STATES.SHIPPED,
  ORDER_STATES.OUT_FOR_DELIVERY,
];