export const PAYMENT_METHODS = {
  UPI_MANUAL: 'UPI_MANUAL',
  COD: 'COD',
} as const;

export type PaymentMethod = (typeof PAYMENT_METHODS)[keyof typeof PAYMENT_METHODS];

export const UPI_PAYMENT_STATES = {
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PROOF_SUBMITTED: 'PROOF_SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
} as const;

export type UpiPaymentState = (typeof UPI_PAYMENT_STATES)[keyof typeof UPI_PAYMENT_STATES];

export const COD_PAYMENT_STATES = {
  COD_PENDING: 'COD_PENDING',
  COD_CONFIRMED: 'COD_CONFIRMED',
} as const;

export type CodPaymentState = (typeof COD_PAYMENT_STATES)[keyof typeof COD_PAYMENT_STATES];

export const PAYMENT_STATES = {
  ...UPI_PAYMENT_STATES,
  ...COD_PAYMENT_STATES,
} as const;

export type PaymentState = (typeof PAYMENT_STATES)[keyof typeof PAYMENT_STATES];

export const UPI_PAYMENT_STATE_SEQUENCE: readonly UpiPaymentState[] = [
  UPI_PAYMENT_STATES.PAYMENT_PENDING,
  UPI_PAYMENT_STATES.PROOF_SUBMITTED,
  UPI_PAYMENT_STATES.UNDER_REVIEW,
  UPI_PAYMENT_STATES.PAYMENT_CONFIRMED,
];

export const PAYMENT_REJECTION_REASONS = {
  PAYMENT_NOT_RECEIVED: 'PAYMENT_NOT_RECEIVED',
  WRONG_AMOUNT: 'WRONG_AMOUNT',
  UNCLEAR_SCREENSHOT: 'UNCLEAR_SCREENSHOT',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
} as const;

export type PaymentRejectionReason =
  (typeof PAYMENT_REJECTION_REASONS)[keyof typeof PAYMENT_REJECTION_REASONS];