export const PERMISSIONS = {
  PRODUCT_READ: 'product.read',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_DELETE: 'product.delete',
  CATEGORY_READ: 'category.read',
  CATEGORY_CREATE: 'category.create',
  CATEGORY_UPDATE: 'category.update',
  CATEGORY_DELETE: 'category.delete',
  VARIANT_READ: 'variant.read',
  VARIANT_CREATE: 'variant.create',
  VARIANT_UPDATE: 'variant.update',
  VARIANT_DELETE: 'variant.delete',
  PRICE_UPDATE: 'price.update',
  MEDIA_UPLOAD: 'media.upload',
  ORDER_READ: 'order.read',
  ORDER_UPDATE: 'order.update',
  ORDER_CANCEL: 'order.cancel',
  ORDER_NOTE: 'order.note',
  PAYMENT_VERIFY: 'payment.verify',
  PAYMENT_REJECT: 'payment.reject',
  REFUND_APPROVE: 'refund.approve',
  REFUND_PROCESS: 'refund.process',
  REFUND_TRACK: 'refund.track',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_UPDATE: 'inventory.update',
  INVENTORY_ADJUST: 'inventory.adjust',
  SUPPLIER_CREATE: 'supplier.create',
  SUPPLIER_UPDATE: 'supplier.update',
  PURCHASE_CREATE: 'purchase.create',
  PURCHASE_UPDATE: 'purchase.update',
  PURCHASE_RECEIVE: 'purchase.receive',
  PRODUCTION_READ: 'production.read',
  PRODUCTION_UPDATE: 'production.update',
  QC_READ: 'qc.read',
  QC_UPDATE: 'qc.update',
  PACKING_UPDATE: 'packing.update',
  SHIPPING_UPDATE: 'shipping.update',
  RETURN_APPROVE: 'return.approve',
  REVIEW_READ: 'review.read',
  REVIEW_MODERATE: 'review.moderate',
  COUPON_CREATE: 'coupon.create',
  COUPON_UPDATE: 'coupon.update',
  COUPON_DELETE: 'coupon.delete',
  OFFER_CREATE: 'offer.create',
  OFFER_UPDATE: 'offer.update',
  OFFER_DELETE: 'offer.delete',
  CMS_CREATE: 'cms.create',
  CMS_UPDATE: 'cms.update',
  CMS_DELETE: 'cms.delete',
  SETTINGS_MANAGE: 'settings.manage',
  ROLE_MANAGE: 'role.manage',
  STAFF_MANAGE: 'staff.manage',
  REPORT_READ: 'report.read',
  REPORT_EXPORT: 'report.export',
  AUDIT_READ: 'audit.read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSIONS) as readonly Permission[];